import 'language_service.dart';

class IngredientService {
  static String translate(String englishTag) {
    final lang = LanguageService.currentLanguage.value;
    
    // Очищаем тег: переводим в нижний регистр, убираем лишние пробелы и заменяем _ на пробел
    String normalized = englishTag.toLowerCase().trim();
    String cleanTag = normalized.replaceAll('_', ' ');
    
    // Сначала ищем по точному совпадению (с подчеркиванием или без)
    if (_translations.containsKey(normalized)) {
      return _translations[normalized]![lang] ?? englishTag;
    }
    if (_translations.containsKey(cleanTag)) {
      return _translations[cleanTag]![lang] ?? englishTag;
    }
    
    return englishTag;
  }

  static final Map<String, Map<String, String>> _translations = {
    'ampalaya': {'ru': 'ампалайя', 'kk': 'ампалайя', 'en': 'ampalaya'},
    'apple': {'ru': 'яблоко', 'kk': 'алма', 'en': 'apple'},
    'asparagus': {'ru': 'спаржа', 'kk': 'спаржа', 'en': 'asparagus'},
    'avocado': {'ru': 'авокадо', 'kk': 'авокадо', 'en': 'avocado'},
    'bacon': {'ru': 'бекон', 'kk': 'бекон', 'en': 'bacon'},
    'bagel': {'ru': 'бейгл', 'kk': 'бейгл', 'en': 'bagel'},
    'banana': {'ru': 'банан', 'kk': 'банан', 'en': 'banana'},
    'beans': {'ru': 'фасоль', 'kk': 'бұршақ', 'en': 'beans'},
    'beef': {'ru': 'говядина', 'kk': 'сиыр еті', 'en': 'beef'},
    'bell pepper': {'ru': 'болгарский перец', 'kk': 'тәтті бұрыш', 'en': 'bell pepper'},
    'bento': {'ru': 'бенто', 'kk': 'бенто', 'en': 'bento'},
    'bitter gourd': {'ru': 'горькая тыква', 'kk': 'ащы асқабақ', 'en': 'bitter gourd'},
    'bitter melon': {'ru': 'горькая дыня', 'kk': 'ащы қауын', 'en': 'bitter melon'},
    'blueberries': {'ru': 'черника', 'kk': 'қаражидек', 'en': 'blueberries'},
    'bok choy': {'ru': 'бок-чой', 'kk': 'бок-чой', 'en': 'bok choy'},
    'bottle': {'ru': 'бутылка', 'kk': 'бөтелке', 'en': 'bottle'},
    'bread': {'ru': 'хлеб', 'kk': 'нан', 'en': 'bread'},
    'broccoli': {'ru': 'брокколи', 'kk': 'брокколи', 'en': 'broccoli'},
    'burdock': {'ru': 'лопух', 'kk': 'ошаған', 'en': 'burdock'},
    'butter': {'ru': 'масло', 'kk': 'май', 'en': 'butter'},
    'cabbage': {'ru': 'капуста', 'kk': 'қырыққабат', 'en': 'cabbage'},
    'cake': {'ru': 'торт', 'kk': 'торт', 'en': 'cake'},
    'can': {'ru': 'банка', 'kk': 'құты', 'en': 'can'},
    'candy': {'ru': 'конфета', 'kk': 'кәмпит', 'en': 'candy'},
    'canned corn': {'ru': 'консервированная кукуруза', 'kk': 'консервіленген жүгері', 'en': 'canned corn'},
    'canned tuna': {'ru': 'консервированный тунец', 'kk': 'консервіленген тунец', 'en': 'canned tuna'},
    'carrot': {'ru': 'морковь', 'kk': 'сәбіз', 'en': 'carrot'},
    'cashew': {'ru': 'кешью', 'kk': 'кешью', 'en': 'cashew'},
    'cauliflower': {'ru': 'цветная капуста', 'kk': 'гүлді қырыққабат', 'en': 'cauliflower'},
    'cereal': {'ru': 'хлопья', 'kk': 'дәмдік хлопьялар', 'en': 'cereal'},
    'cheese': {'ru': 'сыр', 'kk': 'ірімшік', 'en': 'cheese'},
    'cherry': {'ru': 'вишня', 'kk': 'шие', 'en': 'cherry'},
    'chicken': {'ru': 'курица', 'kk': 'тауық', 'en': 'chicken'},
    'chicken breast': {'ru': 'куриная грудка', 'kk': 'тауық төсі', 'en': 'chicken breast'},
    'chicken thigh': {'ru': 'куриное бедро', 'kk': 'тауық саны', 'en': 'chicken thigh'},
    'chicken wing': {'ru': 'куриное крыло', 'kk': 'тауық қанаты', 'en': 'chicken wing'},
    'chili': {'ru': 'чили', 'kk': 'чили', 'en': 'chili'},
    'chili powder': {'ru': 'порошок чили', 'kk': 'чили ұнтағы', 'en': 'chili powder'},
    'chips': {'ru': 'чипсы', 'kk': 'чипсы', 'en': 'chips'},
    'chocolate': {'ru': 'шоколад', 'kk': 'шоколад', 'en': 'chocolate'},
    'cinnamon': {'ru': 'корица', 'kk': 'корица', 'en': 'cinnamon'},
    'coffee': {'ru': 'кофе', 'kk': 'кофе', 'en': 'coffee'},
    'cooking oil': {'ru': 'растительное масло', 'kk': 'өсімдік майы', 'en': 'cooking oil'},
    'corn': {'ru': 'кукуруза', 'kk': 'жүгері', 'en': 'corn'},
    'crab': {'ru': 'краб', 'kk': 'краб', 'en': 'crab'},
    'cream cheese': {'ru': 'сливочный сыр', 'kk': 'кілегейлі ірімшік', 'en': 'cream cheese'},
    'cucumber': {'ru': 'огурец', 'kk': 'қияр', 'en': 'cucumber'},
    'dates': {'ru': 'финики', 'kk': 'құрма', 'en': 'dates'},
    'dumpling': {'ru': 'пельмень', 'kk': 'тұшпара', 'en': 'dumpling'},
    'egg': {'ru': 'яйцо', 'kk': 'жұмыртқа', 'en': 'egg'},
    'eggplant': {'ru': 'баклажан', 'kk': 'баклажан', 'en': 'eggplant'},
    'eggs': {'ru': 'яйца', 'kk': 'жұмыртқалар', 'en': 'eggs'},
    'fish': {'ru': 'рыба', 'kk': 'балық', 'en': 'fish'},
    'flour': {'ru': 'мука', 'kk': 'ұн', 'en': 'flour'},
    'french fries': {'ru': 'картофель фри', 'kk': 'картоп фри', 'en': 'french fries'},
    'garlic': {'ru': 'чеснок', 'kk': 'сарымсақ', 'en': 'garlic'},
    'ginger': {'ru': 'имбирь', 'kk': 'зімбір', 'en': 'ginger'},
    'grape': {'ru': 'виноград', 'kk': 'жүзім', 'en': 'grape'},
    'grapefruit': {'ru': 'грейпфрут', 'kk': 'грейпфрут', 'en': 'grapefruit'},
    'green chili': {'ru': 'зеленый чили', 'kk': 'жасыл чили', 'en': 'green chili'},
    'green onion': {'ru': 'зеленый лук', 'kk': 'көк пияз', 'en': 'green onion'},
    'ground beef': {'ru': 'говяжий фарш', 'kk': 'сиыр тартылған еті', 'en': 'ground beef'},
    'guacamole': {'ru': 'гуакамоле', 'kk': 'гуакамоле', 'en': 'guacamole'},
    'ham': {'ru': 'ветчина', 'kk': 'ветчина', 'en': 'ham'},
    'honey': {'ru': 'мед', 'kk': 'бал', 'en': 'honey'},
    'hotdog': {'ru': 'хот-дог', 'kk': 'хот-дог', 'en': 'hotdog'},
    'humus': {'ru': 'хумус', 'kk': 'хумус', 'en': 'humus'},
    'ice': {'ru': 'лед', 'kk': 'мұз', 'en': 'ice'},
    'jam': {'ru': 'варенье', 'kk': 'тосап', 'en': 'jam'},
    'juice': {'ru': 'сок', 'kk': 'шырын', 'en': 'juice'},
    'ketchup': {'ru': 'кетчуп', 'kk': 'кетчуп', 'en': 'ketchup'},
    'kimchi': {'ru': 'кимчи', 'kk': 'кимчи', 'en': 'kimchi'},
    'kiwi': {'ru': 'киви', 'kk': 'киви', 'en': 'kiwi'},
    'leek': {'ru': 'лук-порей', 'kk': 'порей пиязы', 'en': 'leek'},
    'lemon': {'ru': 'лимон', 'kk': 'лимон', 'en': 'lemon'},
    'lettuce': {'ru': 'салат латук', 'kk': 'салат жапырағы', 'en': 'lettuce'},
    'lime': {'ru': 'лайм', 'kk': 'лайм', 'en': 'lime'},
    'mango': {'ru': 'манго', 'kk': 'манго', 'en': 'mango'},
    'mayonnaise': {'ru': 'майонез', 'kk': 'майонез', 'en': 'mayonnaise'},
    'milk': {'ru': 'молоко', 'kk': 'сүт', 'en': 'milk'},
    'mint': {'ru': 'мята', 'kk': 'жалбыз', 'en': 'mint'},
    'mushroom': {'ru': 'гриб', 'kk': 'саңырауқұлақ', 'en': 'mushroom'},
    'mustard': {'ru': 'горчица', 'kk': 'қыша', 'en': 'mustard'},
    'noodle': {'ru': 'лапша', 'kk': 'кеспе', 'en': 'noodle'},
    'nuts': {'ru': 'орехи', 'kk': 'жаңғақтар', 'en': 'nuts'},
    'oil': {'ru': 'масло', 'kk': 'май', 'en': 'oil'},
    'olive oil': {'ru': 'оливковое масло', 'kk': 'зәйтүн майы', 'en': 'olive oil'},
    'onion': {'ru': 'лук', 'kk': 'пияз', 'en': 'onion'},
    'orange': {'ru': 'апельсин', 'kk': 'апельсин', 'en': 'orange'},
    'pasta': {'ru': 'паста', 'kk': 'паста', 'en': 'pasta'},
    'peach': {'ru': 'персик', 'kk': 'шабдалы', 'en': 'peach'},
    'peanut butter': {'ru': 'арахисовое масло', 'kk': 'арахис майы', 'en': 'peanut butter'},
    'pear': {'ru': 'груша', 'kk': 'алмұрт', 'en': 'pear'},
    'peas': {'ru': 'горох', 'kk': 'бұршақ', 'en': 'peas'},
    'pepper': {'ru': 'перец', 'kk': 'бұрыш', 'en': 'pepper'},
    'pickle': {'ru': 'маринованный огурец', 'kk': 'тұздалған қияр', 'en': 'pickle'},
    'pineapple': {'ru': 'ананас', 'kk': 'ананас', 'en': 'pineapple'},
    'pork': {'ru': 'свинина', 'kk': 'шошқа еті', 'en': 'pork'},
    'potato': {'ru': 'картофель', 'kk': 'картоп', 'en': 'potato'},
    'pumpkin': {'ru': 'тыква', 'kk': 'асқабақ', 'en': 'pumpkin'},
    'radish': {'ru': 'редис', 'kk': 'редис', 'en': 'radish'},
    'rice': {'ru': 'рис', 'kk': 'күріш', 'en': 'rice'},
    'salad': {'ru': 'салат', 'kk': 'салат', 'en': 'salad'},
    'salami': {'ru': 'салями', 'kk': 'салями', 'en': 'salami'},
    'salmon': {'ru': 'лосось', 'kk': 'бақтақ', 'en': 'salmon'},
    'salt': {'ru': 'соль', 'kk': 'тұз', 'en': 'salt'},
    'sandwich': {'ru': 'сэндвич', 'kk': 'сэндвич', 'en': 'sandwich'},
    'sausage': {'ru': 'колбаса', 'kk': 'шұжық', 'en': 'sausage'},
    'shrimp': {'ru': 'креветка', 'kk': 'асшаян', 'en': 'shrimp'},
    'soda': {'ru': 'сода', 'kk': 'сода', 'en': 'soda'},
    'soy sauce': {'ru': 'соевый соус', 'kk': 'соя соусы', 'en': 'soy sauce'},
    'spam': {'ru': 'спам', 'kk': 'спам', 'en': 'spam'},
    'spinach': {'ru': 'шпинат', 'kk': 'шпинат', 'en': 'spinach'},
    'squid': {'ru': 'кальмар', 'kk': 'кальмар', 'en': 'squid'},
    'strawberry': {'ru': 'клубника', 'kk': 'құлпынай', 'en': 'strawberry'},
    'sugar': {'ru': 'сахар', 'kk': 'қант', 'en': 'sugar'},
    'tea': {'ru': 'чай', 'kk': 'шай', 'en': 'tea'},
    'tofu': {'ru': 'тофу', 'kk': 'тофу', 'en': 'tofu'},
    'tomato': {'ru': 'помидор', 'kk': 'қызанақ', 'en': 'tomato'},
    'tuna': {'ru': 'тунец', 'kk': 'тунец', 'en': 'tuna'},
    'turkey': {'ru': 'индейка', 'kk': 'куркетауық', 'en': 'turkey'},
    'vinegar': {'ru': 'уксус', 'kk': 'сірке суы', 'en': 'vinegar'},
    'water': {'ru': 'вода', 'kk': 'су', 'en': 'water'},
    'watermelon': {'ru': 'арбуз', 'kk': 'қарбыз', 'en': 'watermelon'},
    'yogurt': {'ru': 'йогурт', 'kk': 'йогурт', 'en': 'yogurt'},
    'zucchini': {'ru': 'кабачок', 'kk': 'кәді', 'en': 'zucchini'},
  };
}
