// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBArSBWUvGIzHJkL5av9SrLpB5rwISlN2s',
    appId: '1:753013515237:web:edc8538040393b3de2450c',
    messagingSenderId: '753013515237',
    projectId: 'smart-recipe-fxdj',
    authDomain: 'smart-recipe-fxdj.firebaseapp.com',
    storageBucket: 'smart-recipe-fxdj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPlLqWRW8uos6jdkZGDgiyDhA60cERB4M',
    appId: '1:753013515237:android:0eebf4ae813c6cb8e2450c',
    messagingSenderId: '753013515237',
    projectId: 'smart-recipe-fxdj',
    storageBucket: 'smart-recipe-fxdj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQFXFEp2bs_xhc-_tuGE06IQ0w3W59Sg',
    appId: '1:753013515237:ios:624d00efa721ae93e2450c',
    messagingSenderId: '753013515237',
    projectId: 'smart-recipe-fxdj',
    storageBucket: 'smart-recipe-fxdj.firebasestorage.app',
    iosBundleId: 'com.example.prototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiQFXFEp2bs_xhc-_tuGE06IQ0w3W59Sg',
    appId: '1:753013515237:ios:624d00efa721ae93e2450c',
    messagingSenderId: '753013515237',
    projectId: 'smart-recipe-fxdj',
    storageBucket: 'smart-recipe-fxdj.firebasestorage.app',
    iosBundleId: 'com.example.prototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBArSBWUvGIzHJkL5av9SrLpB5rwISlN2s',
    appId: '1:753013515237:web:0e17b41c345833fbe2450c',
    messagingSenderId: '753013515237',
    projectId: 'smart-recipe-fxdj',
    authDomain: 'smart-recipe-fxdj.firebaseapp.com',
    storageBucket: 'smart-recipe-fxdj.firebasestorage.app',
  );
}
